<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'admin' => 'Admin',
    'name' => 'Ism',
    'Address' => 'Address',
    'Apply Time' => 'Bajarish Vaqti',
    'Auth Key' => 'Auth Key',
    'Capacity' => 'Sig\'im',
    'Course ID' => 'Course ID',
    'Created At' => 'Saqlangan Sana',
    'Created By' => 'Saqlagan shaxs',
    'Description' => 'Ta\'rif',
    'Email' => 'Pochta',
    'First Name' => 'Ism',
    'Floor' => 'Qavat',
    'ID' => 'ID',
    'Last Name' => 'Familya',
    'Name' => 'Ism',
    'Password Hash' => 'Password Hash',
    'Password Reset Token' => 'Password Reset Token',
    'Phone' => 'Telefon',
    'Price' => 'Narx',
    'Room ID' => 'Xona ID',
    'Salary' => 'Maosh',
    'Science ID' => 'Yo\'nalish ID',
    'Status' => 'Holat',
    'Student ID' => 'Student ID',
    'Teacher ID' => 'O\'qituvchi',
    'Updated At' => 'O\'zgartirilgan Sana',
    'Updated By' => 'O\'zgartirgan shaxs',
    'User ID' => 'User ID',
    'Username' => 'Username',
    'Verification Token' => 'Verification Token',
    'Version' => 'Versiya',
    'language' => 'Uz',
];
