<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Address',
    'Apply Time' => 'Bajarish Vaqti',
    'Capacity' => 'Sig\'im',
    'Course ID' => 'Course ID',
    'Created At' => 'Saqlangan Sana',
    'Created By' => 'Saqlagan shaxs',
    'Description' => 'Ta\'rif',
    'Email' => 'Pochta',
    'First Name' => 'Ism',
    'Floor' => 'Qavat',
    'ID' => 'ID',
    'Last Name' => 'Familya',
    'Name' => 'Ism',
    'Phone' => 'Telefon',
    'Price' => 'Narx',
    'Room ID' => 'Xona ID',
    'Salary' => 'Maosh',
    'Science ID' => 'Yo\'nalish ID',
    'Status' => 'Holat',
    'Student ID' => 'Student ID',
    'Teacher ID' => 'O\'qituvchi',
    'Updated At' => 'O\'zgartirilgan Sana',
    'Updated By' => 'O\'zgartirgan shaxs',
    'User ID' => 'User ID',
    'Version' => 'Versiya',
    'admin' => 'Admin',
    'ACTIVE' => '',
    'Are you sure you want to delete this item?' => '',
    'Course' => '',
    'Courses' => '',
    'Create Course' => '',
    'Create Group' => '',
    'Create User' => '',
    'DELETED' => '',
    'Delete' => '',
    'Employees' => '',
    'Group' => '',
    'Groups' => '',
    'INACTIVE' => '',
    'Instructor' => '',
    'Password' => '',
    'Room' => '',
    'Science' => '',
    'Student' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update Group: {name}' => '',
    'Update User: {name}' => '',
    'User' => '',
];
