<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'admin' => 'Admin',
    'name' => 'name',
    'Address' => '',
    'Apply Time' => '',
    'Auth Key' => '',
    'Capacity' => '',
    'Course ID' => '',
    'Created At' => '',
    'Created By' => '',
    'Description' => '',
    'Email' => '',
    'First Name' => '',
    'Floor' => '',
    'ID' => '',
    'Last Name' => '',
    'Name' => '',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Phone' => '',
    'Price' => '',
    'Room ID' => '',
    'Salary' => '',
    'Science ID' => '',
    'Status' => '',
    'Student ID' => '',
    'Teacher ID' => '',
    'Updated At' => '',
    'Updated By' => '',
    'User ID' => '',
    'Username' => '',
    'Verification Token' => '',
    'Version' => '',
    'language' => '@@En@@',
];
