<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'admin' => 'Админ',
    'name' => 'Имя',
    'Address' => 'Адрес',
    'Apply Time' => 'Применить время',
    'Auth Key' => 'Ключ авторизации',
    'Capacity' => 'Емкость',
    'Course ID' => 'Курс ID',
    'Created At' => 'Создан в',
    'Created By' => 'Сделано',
    'Description' => 'Описание',
    'Email' => 'Электронная почта',
    'First Name' => 'Имя',
    'Floor' => 'Пол',
    'ID' => 'ID',
    'Last Name' => 'Фамилия',
    'Name' => 'Имя',
    'Password Hash' => 'Хэш пароля',
    'Password Reset Token' => 'Токен сброса пароля',
    'Phone' => 'Телефон',
    'Price' => 'Цена',
    'Room ID' => 'Комната ID',
    'Salary' => 'Зарплата',
    'Science ID' => 'Наука ID',
    'Status' => 'Статус',
    'Student ID' => 'Студент ID',
    'Teacher ID' => 'Учитель ID',
    'Updated At' => 'Обновлено в',
    'Updated By' => 'Обновлено',
    'User ID' => 'Пользователь ID',
    'Username' => 'Username',
    'Verification Token' => 'Токен подтверждения',
    'Version' => 'Версия',
    'language' => 'Ру',
];
